
# name: Auto Submit Google Form

# on:
#   schedule:
#     - cron: '*/15 0-16 * * *'
#   workflow_dispatch:  # Cho phép chạy thủ công

# jobs:
#   submit:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4  # Tải code từ repo
#         with:
#           persist-credentials: true  # Cho phép ghi lại thay đổi

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt
#           sudo apt-get update
#           sudo apt-get install -y chromium-browser chromium-chromedriver

#       - name: Run main script
#         run: |
#           python timerun.py

#       - name: Commit changes if any
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git add time.csv index.txt
#           git commit -m "Updated time.csv and index.txt after form submission" || echo "No changes to commit"
          
          
          
#           # Sau đó push
#           git push
